# permissions for end users to edit instancemanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: prometheus-instance-manager
    app.kubernetes.io/managed-by: kustomize
  name: instancemanager-editor-role
rules:
- apiGroups:
  - instancemanager.example.org
  resources:
  - instancemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instancemanager.example.org
  resources:
  - instancemanagers/status
  verbs:
  - get
