---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - instancemanager.example.org
  resources:
  - instancemanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - instancemanager.example.org
  resources:
  - instancemanagers/finalizers
  verbs:
  - update
- apiGroups:
  - instancemanager.example.org
  resources:
  - instancemanagers/status
  verbs:
  - get
  - patch
  - update
